### ISSUE TITLE
ConnectBot private key import

### ISSUE THREAD

**Issue by alarien** [bradand/XMouse#12]
There is an error message "Error: invalid privatekey: [B@<HEX variable>" when I'm trying to use the key generated with ConnectBot. I've tried the following:
1. Generate keys in ConnectBot (standard settings, RSA 2048)
2. Open "Manage Pubkeys menu"
3. Copy private key
4. Paste it in a file "private" on /sdcard
5. Choose that file in XMouse's "Authentication" settings
6. Try to connect and get "invalid privatekey" error
In the end I just used new PC-generated keys, but it would be great to use already authorized ConnectBot keys.
ConnectBot version: 1.8.6
XMouse version: 2.0.21
Attached are [with few symbols swapped] keys in question.
[ConnectBot (Android).txt](https://github.com/bradand/XMouse/files/120780/ConnectBot.Android.txt)
[ssh-keygen (PC).txt](https://github.com/bradand/XMouse/files/120781/ssh-keygen.PC.txt)

**Comment by bradand** [comment]
I believe for the jsch library that XMouse uses to work you must also have your public key stored in the same directory as your private key (same file name) on the sdcard but with the '.pub' extension.

Give this a try and let me know.

**Comment by bradand** [comment]
The issue explained here may also help:

http://stackoverflow.com/questions/15332120/jsch-invalid-private-key

**Comment by alarien** [comment]
Putting corresponding .pub key in the folder with private key alone didn't solve the problem. PuTTYgen threw "unrecognized key" message on import.

But key conversion from PKCS#8 to PKCS#5 format with command `openssl rsa -in old_key -out new_key` did the trick as in http://sourceforge.net/p/jsch/mailman/jsch-users/thread/52815BAA.1070908%40verizon.net/#msg31626638 and everything is working flawlessly. It seems to be library specific, indeed. So, steps to solve this were:
1. Put corresponding .pub key in the same folder with private key (e.g. /sdcard/.ssh)
2. Convert private key using `openssl rsa -in id_rsa -out new` command

Thank you for great support and brilliant application.
