### ISSUE TITLE
writing/drawing mode

### ISSUE THREAD

**Issue by cyberorg** [bradand/XMouse#45]
With xmouse and stylus I am able to do everything except a handwritten note because the left mouse click can't be locked. Before writing each letter I need to long press on the screen.

Can I request handwriting/drawing mode, it can be done by any of the following.

1. Lock left mouse button press toggle
2. Low long press delay, ideally configurable option.

This will allow more natural writing and drawing.

We intend to use this with openboard in classrooms.

Thanks for the very useful app.

**Comment by pooispoois** [comment]
I agree that this would be a great feature. Even on normal desktops, a standard phone/tablet would allow precision in note taking/drawing.
