### ISSUE TITLE
How to use with SSH key?

### ISSUE THREAD

**Issue by Gooberpatrol66** [bradand/XMouse#46]
All I see is a "password" field and no way to specify a key.

**Comment by marvinbernhardt** [comment]
You can define only one key in the settings. You find the settings in the menu on the top right.

I just had the same problem and i had to go through the code to find out that there is a settings menu. I did not find it initially, because i expected it to be in the left menu, as it is in most apps.

**Comment by Gooberpatrol66** [comment]
Thanks.
