### ISSUE TITLE
Option to unset $HISTFILE on session initiaite

### ISSUE THREAD

**Issue by LukeHandle** [bradand/XMouse#5]
Hey, I think a useful feature would be a setting to `unset $HISTFILE` on session initiate so that all the `xdotool mousemove_relative ...` do not fill the shells history file.

**Comment by bradand** [comment]
Hey, that is a good idea.

Have you tried modifying the initialization command to include your edit?

**Comment by LukeHandle** [comment]
Ahh yes. 

The old "It's already possibly and you were too blind to notice". 

I hadn't considered fully that's what it did :flushed:. It now reads: `export DISPLAY=':0'; unset HISTFILE` and works great. 

Thanks for the pointer!  :+1: Not sure if this is a more preferable default or not.

**Comment by bradand** [comment]
I suppose you could also program a keyboard button or custom script (behind the commands tab) to run an unset command as well as a define command if you wanted to turn on or off the history on the fly

**Comment by LukeHandle** [comment]
That took me like 5 mins to find what on earth you were talking about. Side note: was there a help box displayed at start? I think I remember one but accidently closed it and couldn't see a way to reopen (may have been a different app though). 

Also found a similar menu on the keyboard page by swiping from left to right. 

It might be a good idea to stick one of the 3 bar icons at the top left (next to XMouse logo) which can be hit to open the same menu.

**Comment by bradand** [comment]
no help box

references to the customizable buttons and scripts are made in the description and app photos. polishes like the icons you mentioned were left absent due to time constraints

**Comment by Drugoy** [comment]
For some reason the suggested solution doesn't seem to work for me.
It works locally for me just fine (I use zsh and it relies on that ENV), but with XMouse I still get xdotool commands concatenated to the history.
v2.0.27
