### ISSUE TITLE
App crash after fedora 22 upgrade of openssh-server from 6.8p1-8.fc22.x86_64 to 6.9p1-1.fc22.x86_64

### ISSUE THREAD

**Issue by AAccount** [bradand/XMouse#6]
After doing a dnf update on fedora yesterday, I wanted to use this app as my remote control as I usually do but every time I try to connect it crashes with this logcat:

W/art     (21931): Unresolved exception class when finding catch block: org.ietf.jgss.GSSException
E/AndroidRuntime(21931): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime(21931): Process: com.stripe1.xmouse, PID: 21931
E/AndroidRuntime(21931): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(21931): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(21931): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(21931): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(21931): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(21931): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(21931): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(21931): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(21931): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(21931): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/ietf/jgss/Oid;
E/AndroidRuntime(21931): 	at com.jcraft.jsch.jgss.GSSContextKrb5.create(GSSContextKrb5.java:55)
E/AndroidRuntime(21931): 	at com.jcraft.jsch.UserAuthGSSAPIWithMIC.start(UserAuthGSSAPIWithMIC.java:125)
E/AndroidRuntime(21931): 	at com.jcraft.jsch.Session.connect(Session.java:463)
E/AndroidRuntime(21931): 	at com.stripe1.xmouse.tasks.SshConnectTask.doInBackground(SshConnectTask.java:53)
E/AndroidRuntime(21931): 	at com.stripe1.xmouse.tasks.SshConnectTask.doInBackground(SshConnectTask.java:1)
E/AndroidRuntime(21931): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(21931): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(21931): 	... 4 more
E/AndroidRuntime(21931): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.ietf.jgss.Oid" on path: DexPathList[[zip file "/data/app/com.stripe1.xmouse-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(21931): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(21931): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(21931): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(21931): 	... 11 more
E/AndroidRuntime(21931): 	Suppressed: java.lang.ClassNotFoundException: org.ietf.jgss.Oid
E/AndroidRuntime(21931): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(21931): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(21931): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(21931): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(21931): 		... 12 more
E/AndroidRuntime(21931): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager(  416):   Force finishing activity 1 com.stripe1.xmouse/.MainActivity

After a bit of googling I found this https://stackoverflow.com/questions/28411153/jsch-suppressed-java-lang-classnotfoundexception-lorg-ietf-jgss-oid

I added the recommended line right before MainActivity.session.connect and it didn't crash anymore.

**Comment by bradand** [comment]
Thanks for the information!

**Comment by bradand** [comment]
I believe I have added your suggested code in the new version v16 (2.0.17)
