### ISSUE TITLE
Cannot send @ character with keyboard

### ISSUE THREAD

**Issue by VictorLamoine** [bradand/XMouse#7]
`@` characters (and maybe others) are not sent when in keyboard mode

**Comment by bradand** [comment]
I am not able to reproduce this error. I just tried it and the '@' symbols come across just fine. You will need to give some more details.

**Comment by VictorLamoine** [comment]
Ubuntu 14.04
xdotool version 3.20140217.1

I tried this again, I can reproduce the bug but most of the time the `@` character is sent.
What can I do to trace the bug on my android? (I guess it's on the Android side?)

**Comment by VictorLamoine** [comment]
On my machine (not through SSH):
```bash
$ xdotool type '@'
⅛victor@desktop:~$ ⅛
```

I tried ` export LANG=C` but it doesn't change anything.

**Comment by bradand** [comment]
Hmm seems like your key definitions are different than mine?

What do you have on line 571 of file /usr/include/X11/keysymdef.h ? I have:

#define XK_at                0x0040 /*   U+0040 COMMERCIAL AT */

**Comment by VictorLamoine** [comment]
Line 577:
```cpp
#define XK_at         0x0040  /* U+0040 COMMERCIAL AT */
```

**Comment by bradand** [comment]
ok what about the output of this command:

setxkbmap -query -v 10

**Comment by VictorLamoine** [comment]
```bash
$ setxkbmap -query -v 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     fr,us,fr
variant:    ,,oss
Trying to build keymap using the following components:
keycodes:   evdev+aliases(azerty)
types:      complete
compat:     complete
symbols:    pc+fr+us:2+fr(oss):3+inet(evdev)
geometry:   pc(pc105)
rules:      evdev
model:      pc105
layout:     fr,us,fr
variant:    ,,oss
```

**Comment by bradand** [comment]
It seems that you have a non-default keyboard layout defined. Try running this command:

sudo dpkg-reconfigure keyboard-configuration

Select: Generic 105-key (Intl) PC > English (US) > English (US) > "the default..." > "no compose key" > "no"

Hopefully this will fix your issue.

**Comment by VictorLamoine** [comment]
This solved the problem and now I can send special characters!
Thanks for the support and great app :+1:
